<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

// phpcs:disable Generic.Files.LineLength

/** @var \Vendic\RUMVision\ViewModel\Configuration $configuration */
$configuration = $block->getConfiguration();
?>
<?php if ($configuration->isEnabled() && $configuration->getRumVisionTrackingId()) : ?>
    <!-- RUMVision tracking code -->
    <script>
        window.rumv = window.rumv || function() { (window.rumv.q = window.rumv.q || []).push(arguments) };
        (function(rum, vi,si,on) {
            var s = JSON.parse( sessionStorage.getItem('rumv') || '{"pageviews":0}' ); s.pageviews++;
            if ( s.urls && s.regex && ( s.page = eval('('+s.regex+')')( s.urls, on.pathname ) ) && !s.page.type ) {
                return sessionStorage.setItem('rumv', JSON.stringify( s ) );
            }

            var head = si.querySelector('head'), js = si.createElement('script');
            js.src = 'https://d5yoctgpv4cpx.cloudfront.net/RUM-'+rum+'/v3-'+on.hostname+'.js';
            vi.rumv.storage = s;
            head.appendChild(js);
        })( '<?= $escaper->escapeHtml($configuration->getRumVisionTrackingId()) ?>', window, document, location, '<?= $escaper->escapeHtml($configuration->getRumVisionDomain()) ?>' );
    </script>
<?php endif; ?>
